import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-blue-500 text-white p-4 flex flex-wrap justify-between items-center">
          <div className="flex gap-1 m:gap-4">
            <Link
              href="/buildings"
              className="hover:bg-blue-600 px-4 py-2 rounded-md"
            >
              Building
            </Link>
            <Link
              href="/campuses"
              className="hover:bg-blue-600 px-4 py-2 rounded-md"
            >
              Campuses
            </Link>
            <Link
              href="/rooms"
              className="hover:bg-blue-600 px-4 py-2 rounded-md"
            >
              Rooms
            </Link>
            <Link
              href="/components"
              className="hover:bg-blue-600 px-4 py-2 rounded-md"
            >
              Components
            </Link>
          </div>
          <div className="flex gap-4">
            <Link href="/" className="hover:bg-blue-600 px-4 py-2 rounded-md">
              Main Page
            </Link>
          </div>
        </nav>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
